services:
  frontend:
    build:
      context: ./svelte_frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./fastapi_backend/.env.docker
    environment:
    - RUNNING_IN_DOCKER=true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
