services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Migration service - only runs migrations
  migrate:
    build: 
      context: ./fastapi_backend
      dockerfile: Dockerfile
    env_file: 
      - ./fastapi_backend/.env.docker
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
    command: ["/migrate.sh", "none"]
    profiles: ["migrate"]

  # Migration + minimal seeding (content types and tools)
  seed-minimal:
    build: 
      context: ./fastapi_backend
      dockerfile: Dockerfile
    env_file: 
      - ./fastapi_backend/.env.docker
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
    command: ["/migrate.sh", "minimal"]
    profiles: ["seed-minimal"]

  # Migration + full seeding (all data)
  seed-full:
    build: 
      context: ./fastapi_backend
      dockerfile: Dockerfile
    env_file: 
      - ./fastapi_backend/.env.docker
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
    command: ["/migrate.sh", "full"]
    profiles: ["seed-full"]

  backend:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./fastapi_backend/.env.docker
    environment:
      - RUNNING_IN_DOCKER=true
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./svelte_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
