"""added sort_order to group_snippet

Revision ID: 00102ad97c0b
Revises: 40b6ddbe4855
Create Date: 2025-06-17 13:46:20.385684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00102ad97c0b'
down_revision: Union[str, None] = '40b6ddbe4855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_snippet', sa.Column('sort_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_snippet', 'sort_order')
    # ### end Alembic commands ###
