"""Add last_updated

Revision ID: 1bc962e9d242
Revises: f40995b02e59
Create Date: 2025-08-27 09:32:08.521187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc962e9d242'
down_revision: Union[str, None] = 'f40995b02e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('layer', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stories', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('terrain_providers', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tool', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'last_updated')
    op.drop_column('terrain_providers', 'last_updated')
    op.drop_column('stories', 'last_updated')
    op.drop_column('projects', 'last_updated')
    op.drop_column('layer', 'last_updated')
    op.drop_column('bookmarks', 'last_updated')
    # ### end Alembic commands ###
