"""placed is_default boolean into the layer junction table

Revision ID: 2703b42bb923
Revises: 75c48a9e4e46
Create Date: 2025-06-23 15:12:52.657687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2703b42bb923'
down_revision: Union[str, None] = '75c48a9e4e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin_layer_association', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.drop_column('layer', 'defaultOn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('defaultOn', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('digital_twin_layer_association', 'is_default')
    # ### end Alembic commands ###
