"""Removed thumbnail from digital_twin table

Revision ID: 2e5d7b05f8f3
Revises: 1a053d8c87f2
Create Date: 2025-06-23 11:50:07.336470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5d7b05f8f3'
down_revision: Union[str, None] = '1a053d8c87f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_twin', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
