"""create all tables

Revision ID: 40b6ddbe4855
Revises: 8f6f88cc5711
Create Date: 2025-06-17 13:14:49.485574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b6ddbe4855'
down_revision: Union[str, None] = '8f6f88cc5711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_twin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_digital_twin_id'), 'digital_twin', ['id'], unique=False)
    op.create_table('layer_snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('beschrijving', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('featureName', sa.String(), nullable=True),
    sa.Column('isBackground', sa.Boolean(), nullable=True),
    sa.Column('defaultOn', sa.Boolean(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layer_snippet_id'), 'layer_snippet', ['id'], unique=False)
    op.create_table('tool_snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_snippet_id'), 'tool_snippet', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('digital_twin_layer_association',
    sa.Column('digital_twin_id', sa.Integer(), nullable=False),
    sa.Column('layer_snippet_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digital_twin_id'], ['digital_twin.id'], ),
    sa.ForeignKeyConstraint(['layer_snippet_id'], ['layer_snippet.id'], ),
    sa.PrimaryKeyConstraint('digital_twin_id', 'layer_snippet_id')
    )
    op.create_table('digital_twin_tool_association',
    sa.Column('digital_twin_id', sa.Integer(), nullable=False),
    sa.Column('tool_snippet_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digital_twin_id'], ['digital_twin.id'], ),
    sa.ForeignKeyConstraint(['tool_snippet_id'], ['tool_snippet.id'], ),
    sa.PrimaryKeyConstraint('digital_twin_id', 'tool_snippet_id')
    )
    op.create_table('group_snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('digital_twin_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['digital_twin_id'], ['digital_twin.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['group_snippet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_snippet_id'), 'group_snippet', ['id'], unique=False)
    op.create_table('viewer_snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('digital_twin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['digital_twin_id'], ['digital_twin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digital_twin_id')
    )
    op.create_index(op.f('ix_viewer_snippet_id'), 'viewer_snippet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewer_snippet_id'), table_name='viewer_snippet')
    op.drop_table('viewer_snippet')
    op.drop_index(op.f('ix_group_snippet_id'), table_name='group_snippet')
    op.drop_table('group_snippet')
    op.drop_table('digital_twin_tool_association')
    op.drop_table('digital_twin_layer_association')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tool_snippet_id'), table_name='tool_snippet')
    op.drop_table('tool_snippet')
    op.drop_index(op.f('ix_layer_snippet_id'), table_name='layer_snippet')
    op.drop_table('layer_snippet')
    op.drop_index(op.f('ix_digital_twin_id'), table_name='digital_twin')
    op.drop_table('digital_twin')
    # ### end Alembic commands ###
