"""Add ON DELETE CASCADE to group.digital_twin_id

Revision ID: 62b6e41daf77
Revises: 76881537e1ac
Create Date: 2025-06-18 16:09:49.795896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b6e41daf77'
down_revision: Union[str, None] = '76881537e1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_digital_twin_id_fkey'), 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'digital_twin', ['digital_twin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key(op.f('group_digital_twin_id_fkey'), 'group', 'digital_twin', ['digital_twin_id'], ['id'])
    # ### end Alembic commands ###
