"""Renaming private to isPrivate

Revision ID: 694da2209ef8
Revises: dad9e9064da6
Create Date: 2025-09-01 16:00:02.649792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694da2209ef8'
down_revision: Union[str, None] = 'dad9e9064da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin', sa.Column('isPrivate', sa.Boolean(), nullable=True))
    op.drop_column('digital_twin', 'private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('digital_twin', 'isPrivate')
    # ### end Alembic commands ###
