"""removed sort order from tool association table

Revision ID: 782d5afba9d0
Revises: c212958cacdc
Create Date: 2025-06-23 14:13:32.764292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '782d5afba9d0'
down_revision: Union[str, None] = 'c212958cacdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_twin_tool_association', 'sort_order')
    op.alter_column('viewer', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viewer', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('digital_twin_tool_association', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
