"""Added owner, private and last_updated field to digital_twin

Revision ID: 7f0fd388f206
Revises: 2703b42bb923
Create Date: 2025-06-26 12:07:50.575081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0fd388f206'
down_revision: Union[str, None] = '2703b42bb923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('digital_twin', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('digital_twin', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_twin', 'last_updated')
    op.drop_column('digital_twin', 'private')
    op.drop_column('digital_twin', 'owner')
    # ### end Alembic commands ###
