"""Added content to digital twin layer relation table

Revision ID: 9317062d7a82
Revises: 694da2209ef8
Create Date: 2025-09-02 10:04:54.211860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9317062d7a82'
down_revision: Union[str, None] = '694da2209ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin_layer_association', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_twin_layer_association', 'content')
    # ### end Alembic commands ###
