"""Add content to tool association polymorph table

Revision ID: f40995b02e59
Revises: 295f1108e155
Create Date: 2025-08-13 10:41:05.490826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40995b02e59'
down_revision: Union[str, None] = '295f1108e155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_twin_tool_association', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_twin_tool_association', 'content')
    # ### end Alembic commands ###
